### ISSUE TITLE
custom report and my try

### ISSUE THREAD

**Issue by sumangongali** [redfish4ktc/maven-soapui-extension-plugin#148]
Hi RedFish,
I have tried below 
1. extended TestcaseRunner  and added newReoprt collector using your factory class
![image](https://user-images.githubusercontent.com/13965714/33685654-51daf79c-daf8-11e7-9695-0049f9a243fd.png)

2. extended report class with your factory class

![image](https://user-images.githubusercontent.com/13965714/33685711-7bda70fe-daf8-11e7-91b9-d18fae7de5dd.png)

3. made a jar file and kept it in the soapui lib folder
4. while starting soapui testRunner  i have added the property soapui.junit.reportCollector=customjunitReport.CustomReportCollector

![image](https://user-images.githubusercontent.com/13965714/33685838-d6691322-daf8-11e7-846d-af337ffa7674.png)

junit reports are not pickked up my changes .
please help me .. invested 5 days still no result

**Comment by redfish4ktc** [comment]
Hello, sorry for the long delay

By default, SoapUI uses its own testRunner and not your custom one.

So to use your custom testRunner, update the testRunner.sh/bat located in the $SOAPUI_HOME/bin directory and put the custom testRunner instead of the default one. If you do not want to modify the original script make a copy
Then it should also work from the UI as it calls the testRunner script (you can change the testRunner script path in the "Basic" tab) and from the command line.

Hope this helps.

**Comment by redfish4ktc** [comment]
Closing as this is an old thread. Feel free to reopen if you need more information.
